# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRAheYklVPIxSpL5MOosyYSs0QW95wtP
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
d=pd.read_csv('titanic.csv')
d

print(d.info())

print(d.describe())

print(d['Survived'].value_counts())

print(d.isnull().sum())

d.drop('Cabin',axis=1,inplace=True,errors='ignore')
d

d_1=d[~d['Embarked'].isnull()]
d_1

d_1.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns
sns.histplot(d['Age'], kde=True)
plt.title('Age Distribution')
plt.show()

"""This histogram and KDE plot visualize the age distribution in your dataset. The main observations are:

The distribution has a significant peak at around age 28, indicating a large concentration of individuals at this age.

There are smaller peaks in the lower age range (e.g., ages 0–10), but a sharp and notable spike at 28 stands out distinctly.

After this peak, the frequency gradually decreases, showing that older ages are less common in the data.

The distribution is right-skewed, with fewer individuals at higher ages and a longer tail extending to about age 80.

The KDE curve confirms these trends, showing a spike at 28 and a general decline as the age increases.

These patterns suggest the dataset may be focused on a population where age 28 is highly overrepresented, possibly due to sampling or data collection characteristics.








"""

sns.pairplot(d, vars=['Age', 'Fare', 'Pclass'], hue='Survived')
plt.show()

"""Passengers in first class (Pclass 1) and those who paid higher fares had better survival chances.

Younger children and first-class adults were more likely to survive than other groups.

Most non-survivors were in third class with lower fares and were typically young adults or middle-aged
"""

numeric_df= d.select_dtypes(include=['number'])
corr_matrix=numeric_df.corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

"""Survival is most strongly linked to class (Pclass) and fare.

Higher class (lower Pclass) and higher fare increase survival chances.

Most other correlations are weak or near zero
"""

sns.boxplot(x='Survived', y='Age', data=d)
plt.title('Age vs Survival')
plt.show()

"""The boxplot shows that the median ages of survivors and non-survivors are similar, but there is a wider age range among survivors, including more children and elderly. Most passengers, regardless of survival, were young to middle-aged adults."""

plt.figure(figsize=(8,6))
sns.scatterplot(x='Age', y='SibSp', hue='Survived', data=d)
plt.title('Scatter Plot: Age vs SibSp (colored by Survived)')
plt.xlabel('Age')
plt.ylabel('Number of Siblings/Spouses Aboard (SibSp)')
plt.show()

"""Most passengers had zero or one sibling/spouse aboard, regardless of age or survival. Survival did not clearly depend on SibSp or age, but families with several siblings/spouses were mainly younger, and included both survivors and non-survivors"""

sns.countplot(x='Pclass', hue='Survived', data=d)
plt.title('Survival Trend by Passenger Class')
plt.show()

"""Survival was highest in first class, moderate in second class, and lowest in third class. Most third-class passengers did not survive, while more first-class passengers survived than died"""



"""Provide summary of finding

 Survival chances increased with higher passenger class and higher fare.

Most non-survivors traveled in third class, while most first-class passengers survived.

Age had little effect on survival, but survivors included more children and elderly.

Most passengers had few siblings/spouses aboard; family structure showed no clear survival trend.

Correlations between features were generally weak, except for strong links between class and fare, and class and survival
"""